import type {
  GeneratedCards,
  EvaluationResult,
  GeneratedActiveRecall,
  AutoGeneratedCards,
  AutoGeneratedFlashcard
} from '../types'

// ═══════════════════════════════════════════════════════════════════════════════
// BASIC PROMPTS (ported from studyhelper/src/lib/gemini.ts — kept exactly as-is)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Build a basic card generation prompt
 */
export function buildCardGenerationPrompt(
  extractedText: string,
  minCards: number = 10,
  minQuestions: number = 5
): string {
  return `You are an expert educator and cognitive scientist creating study materials from the following course content.

CONTENT:
${extractedText}

Generate the following in valid JSON:
1. "flashcards": An array of at least ${minCards} flashcards. Each has "front" (term/concept) and "back" (definition/explanation). Make them precise, clear, and educational. Do not generate trivial or redundant cards.
2. "active_recall": An array of at least ${minQuestions} active recall questions. Each has "question" (open-ended, requires understanding) and "model_answer" (a complete, correct answer a student should give).

Prioritize depth over quantity — every card must earn its place. Cover all major topics in the material.

Return ONLY valid JSON. No markdown. No commentary.`
}

/**
 * Build the answer evaluation prompt
 */
export function buildEvaluationPrompt(
  question: string,
  modelAnswer: string,
  studentAnswer: string
): string {
  return `You are grading a student's answer to a study question.

QUESTION: ${question}
MODEL ANSWER: ${modelAnswer}
STUDENT ANSWER: ${studentAnswer}

Evaluate the student's answer and respond in JSON:
{
  "correct": true or false,
  "score": 0-5,
  "feedback": "Specific, constructive feedback. What did they get right? What did they miss? What is the key concept they should understand?"
}

Be fair but academically rigorous. Partial credit answers that capture the core concept should be marked correct.
Return ONLY valid JSON.`
}

/**
 * Parse the card generation response (basic format)
 */
export function parseCardGenerationResponse(responseText: string): GeneratedCards {
  // Strip markdown code fences if present
  let cleaned = responseText.trim()
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
  }

  const parsed = JSON.parse(cleaned)

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }
  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  // Validate flashcard structure
  const flashcards = parsed.flashcards.map((fc: { front?: string; back?: string }) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return { front: fc.front, back: fc.back }
  })

  // Validate active recall structure
  const active_recall = parsed.active_recall.map((ar: { question?: string; model_answer?: string }) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return { question: ar.question, model_answer: ar.model_answer }
  })

  return { flashcards, active_recall }
}

/**
 * Parse the evaluation response
 */
export function parseEvaluationResponse(responseText: string): EvaluationResult {
  let cleaned = responseText.trim()
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
  }

  const parsed = JSON.parse(cleaned)

  if (typeof parsed.correct !== 'boolean') {
    throw new Error('Invalid evaluation response: missing correct field')
  }
  if (typeof parsed.score !== 'number') {
    throw new Error('Invalid evaluation response: missing score field')
  }
  if (typeof parsed.feedback !== 'string') {
    throw new Error('Invalid evaluation response: missing feedback field')
  }

  return {
    correct: parsed.correct,
    score: parsed.score,
    feedback: parsed.feedback
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENHANCED PROMPTS (ported from neuron-web/src/lib/gemini.ts)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Build an enhanced card generation prompt that includes subject/module context
 * and existing cards to avoid duplication
 */
export function buildAutoCardGenerationPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  topicTitle?: string,
  existingCards?: { front: string; back?: string }[],
  minCards: number = 8,
  minQuestions: number = 4
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`
  if (topicTitle) contextSection += `\nTOPIC: ${topicTitle}`

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any concepts, questions, or terms already covered in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
If a topic is already covered above, find fresh angles, deeper mechanisms, distinct applications, or unaddressed subtopics.`
  }

  return `You are a world-class cognitive scientist, learning engineer, and educational prompt designer.
Your mission is to generate high-yield, durable study materials optimized for spaced repetition and deep semantic retention.

CONTEXT:${contextSection}

SOURCE MATERIAL:
${extractedText}

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "flashcards": [
    {
      "front": "Atomic prompt or cloze deletion (e.g. '[Concept] is the mechanism where ___')",
      "back": "Concise, precise explanation (1-2 sentences)",
      "card_subtype": "definition | mechanism | application | discrimination",
      "concrete_example": "A concrete real-world scenario or analogy illustrating this concept",
      "common_mistake": "A frequent student misconception or trap to avoid",
      "mnemonic": "An intuitive memory hook, acronym, or vivid mental visual"
    }
  ],
  "active_recall": [
    {
      "question": "Deep conceptual inquiry starting with Why/How/Explain the mechanism of... or scenario analysis",
      "model_answer": "Complete, structured explanation with key conceptual checkpoints for mastery",
      "card_subtype": "definition | mechanism | application | discrimination",
      "concrete_example": "A real-world application or case study",
      "common_mistake": "A common reasoning flaw or incorrect assumption",
      "mnemonic": "Optional memory aid or mental framework"
    }
  ]
}

## COGNITIVE SCIENCE CARD DESIGN RULES (MUST FOLLOW)

1. **Minimum Information Principle (MIP / Atomicity)**:
   - Each flashcard MUST test EXACTLY ONE atomic fact or relationship.
   - NEVER create compound cards or lists (e.g. "What are the 4 stages of X?"). Split multi-part ideas into separate single-concept cards.

2. **Retrieval Strength & Anti-Pattern Matching**:
   - Prompts must force active semantic retrieval, not superficial keyword recognition or guessing.
   - Make prompts self-contained: NEVER use vague pronouns ("this method", "as discussed above", "the latter").

3. **Cloze Deletions & Targeted Direct Questions for Flashcards**:
   - For terminology and definitions, use precise cloze deletion: "[TERM] is the biological process by which ___".
   - For functional relationships: "What is the primary physiological role of [Concept] in [Context]?"

4. **Elaborative Interrogation for Active Recall**:
   - Every active recall question MUST require causal reasoning, mechanism tracing ("Why does X lead to Y?"), or structural explanation ("How does [A] compensate when [B] fails?").

5. **Concept Discrimination & Boundary Testing**:
   - For easily confused terms or related concepts, construct explicit discrimination cards: "What is the critical functional difference between [X] and [Y]?"

6. **Dual-Coding & Misconception Inoculation**:
   - Every item MUST include a tangible real-world example in "concrete_example".
   - Include the most frequent student misconception in "common_mistake".

## GENERATION TARGETS
- Generate at least ${minCards} flashcards and ${minQuestions} active recall questions.
- Distribute evenly across all major concepts in the source material.${dedupSection}

Return ONLY valid JSON. No markdown fences. No preamble.`
}

/**
 * Build a prompt that requests flashcards ONLY (no active recall).
 */
export function buildFlashcardOnlyPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  minCards: number = 10,
  existingCards?: { front: string; back?: string }[]
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any concepts, questions, or terms already covered in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
Generate cards strictly for new, unaddressed terms and subconcepts.`
  }

  return `You are a world-class cognitive scientist, learning engineer, and educational prompt designer.
Your mission is to generate high-yield, durable flashcards engineered for spaced repetition and rapid semantic retrieval.

CONTEXT:${contextSection}

SOURCE MATERIAL:
${extractedText}

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "flashcards": [
    {
      "front": "Question, prompt, or cloze deletion (e.g. '[TERM] is the process by which ___')",
      "back": "Precise, concise answer/explanation (1-2 sentences)",
      "card_subtype": "definition | mechanism | application | discrimination",
      "concrete_example": "A concrete real-world scenario or analogy illustrating this concept",
      "common_mistake": "A frequent student misconception or trap to avoid",
      "mnemonic": "An intuitive memory hook, acronym, or vivid mental visual"
    }
  ]
}

## FLASHCARD DESIGN RULES (MUST FOLLOW)

1. **Minimum Information Principle (Atomicity)**:
   - Each card tests EXACTLY ONE relationship, term, or concept.
   - Absolutely NO compound lists or multi-part enumerations on the back.

2. **Cloze Deletion & Targeted Questioning**:
   - Use fill-in-the-blank style for core definitions: "[TERM] is the process by which ___".
   - Use direct questions for key properties: "What triggers the activation of [Concept] in [Context]?"

3. **Self-Containment & Unambiguous Retrieval**:
   - Prompts must stand completely on their own without external context or vague pronouns ("as mentioned above", "this process").

4. **Rich Semantic Hooks**:
   - Provide high-value "concrete_example", "common_mistake", and "mnemonic" fields for every card to facilitate multi-modal encoding.

5. **Generate at least ${minCards} flashcards** — Cover all distinct concepts, definitions, and mechanisms evenly.

6. **NO active recall questions.** Flashcards only.${dedupSection}

Return ONLY valid JSON. No markdown fences. No commentary.`
}

/**
 * Build a prompt that requests active recall questions ONLY (no flashcards).
 */
export function buildActiveRecallOnlyPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  minQuestions: number = 6,
  existingCards?: { front: string; back?: string }[]
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any questions or scenarios already present in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
Generate novel questions exploring unaddressed mechanisms, deeper edge cases, or distinct applications.`
  }

  return `You are a world-class cognitive scientist, learning engineer, and educational prompt designer.
Your mission is to generate high-yield active recall questions designed for elaborative interrogation, causal reasoning, and deep conceptual mastery.

CONTEXT:${contextSection}

SOURCE MATERIAL:
${extractedText}

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "active_recall": [
    {
      "question": "Open-ended inquiry requiring deep conceptual understanding (Why/How/Explain/Compare/Analyze)",
      "model_answer": "Complete, rigorous model answer highlighting the core conceptual criteria",
      "card_subtype": "definition | mechanism | application | discrimination",
      "concrete_example": "A real-world application, case study, or problem scenario",
      "common_mistake": "A common logical flaw, incomplete explanation, or misconception",
      "mnemonic": "Optional mental framework or memory aid"
    }
  ]
}

## ACTIVE RECALL QUESTION DESIGN RULES (MUST FOLLOW)

1. **Elaborative Interrogation & Causal Reasoning**:
   - Questions must demand deep causal explanation ("Why does [X] occur when [Y] happens?", "How does [Mechanism A] achieve [Outcome B]?").
   - Avoid shallow factual lookups or simple single-word answers.

2. **Scenario Application & Problem Solving**:
   - Include scenario-based questions: "If a system encounters [Condition X], what occurs at [Level Y] and why?"

3. **Concept Discrimination (Interference Reduction)**:
   - For confusable concepts, ask boundary-testing comparison questions: "How does [Concept A] differ from [Concept B] in terms of [Specific Function]?"

4. **Rigorous Model Answers**:
   - Provide clear, comprehensive model answers with the key checkpoints needed for self-grading or AI evaluation.

5. **Self-Containment**:
   - Every question must be fully understandable without external pointers or vague references.

6. **Generate at least ${minQuestions} active recall questions** — Covering all major topics in depth.

7. **NO flashcards.** Active recall questions only.${dedupSection}

Return ONLY valid JSON. No markdown fences. No commentary.`
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENHANCED PARSERS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Parse the auto-card generation response (extended format with subtypes, examples, etc.)
 */
export function parseAutoCardResponse(responseText: string): AutoGeneratedCards {
  let cleaned = responseText.trim()
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
  }

  const parsed = JSON.parse(cleaned)

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }
  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  const validSubtypes = ['definition', 'mechanism', 'application', 'discrimination'] as const
  type CardSubtype = typeof validSubtypes[number]

  const parseCardSubtype = (val: unknown): CardSubtype | undefined =>
    validSubtypes.includes(val as CardSubtype) ? (val as CardSubtype) : undefined

  const flashcards = parsed.flashcards.map((fc: Record<string, unknown>) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return {
      front: fc.front,
      back: fc.back,
      card_subtype: parseCardSubtype(fc.card_subtype),
      concrete_example: typeof fc.concrete_example === 'string' ? fc.concrete_example : undefined,
      common_mistake: typeof fc.common_mistake === 'string' ? fc.common_mistake : undefined,
      mnemonic: typeof fc.mnemonic === 'string' ? fc.mnemonic : undefined
    } as AutoGeneratedFlashcard
  })

  const active_recall = parsed.active_recall.map((ar: Record<string, unknown>) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return {
      question: ar.question,
      model_answer: ar.model_answer,
      card_subtype: typeof ar.card_subtype === 'string' ? ar.card_subtype : undefined,
      concrete_example: typeof ar.concrete_example === 'string' ? ar.concrete_example : undefined,
      common_mistake: typeof ar.common_mistake === 'string' ? ar.common_mistake : undefined,
      mnemonic: typeof ar.mnemonic === 'string' ? ar.mnemonic : undefined
    }
  })

  return { flashcards, active_recall }
}

/**
 * Parse a flashcard-only response (returns just the flashcards array)
 */
export function parseFlashcardResponse(responseText: string): AutoGeneratedFlashcard[] {
  let cleaned = responseText.trim()
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
  }

  const parsed = JSON.parse(cleaned)

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }

  const validSubtypes = ['definition', 'mechanism', 'application', 'discrimination'] as const
  type CardSubtype = typeof validSubtypes[number]
  const parseCardSubtype = (val: unknown): CardSubtype | undefined =>
    validSubtypes.includes(val as CardSubtype) ? (val as CardSubtype) : undefined

  return parsed.flashcards.map((fc: Record<string, unknown>) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return {
      front: fc.front,
      back: fc.back,
      card_subtype: parseCardSubtype(fc.card_subtype),
      concrete_example: typeof fc.concrete_example === 'string' ? fc.concrete_example : undefined,
      common_mistake: typeof fc.common_mistake === 'string' ? fc.common_mistake : undefined,
      mnemonic: typeof fc.mnemonic === 'string' ? fc.mnemonic : undefined
    } as AutoGeneratedFlashcard
  })
}

/**
 * Parse an active-recall-only response (returns just the active_recall array)
 */
export function parseActiveRecallResponse(
  responseText: string
): (GeneratedActiveRecall & {
  card_subtype?: string
  concrete_example?: string
  common_mistake?: string
  mnemonic?: string
})[] {
  let cleaned = responseText.trim()
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
  }

  const parsed = JSON.parse(cleaned)

  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  return parsed.active_recall.map((ar: Record<string, unknown>) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return {
      question: ar.question,
      model_answer: ar.model_answer,
      card_subtype: typeof ar.card_subtype === 'string' ? ar.card_subtype : undefined,
      concrete_example: typeof ar.concrete_example === 'string' ? ar.concrete_example : undefined,
      common_mistake: typeof ar.common_mistake === 'string' ? ar.common_mistake : undefined,
      mnemonic: typeof ar.mnemonic === 'string' ? ar.mnemonic : undefined
    }
  })
}
