import type {
  GeneratedCards,
  EvaluationResult,
  AutoGeneratedCards,
  AutoGeneratedFlashcard,
  AutoGeneratedActiveRecall,
  ConceptualLens,
  BloomLevel,
  CardTypology
} from '../types'
import { repairJSONString, cleanMarkdownFences } from './jsonRepair'
import { cleanCardBrackets } from './cardParser'

// ═══════════════════════════════════════════════════════════════════════════════
// SHARED PEDAGOGICAL CONSTANTS & C.R.E.A.T.E. EXEMPLARS
// ═══════════════════════════════════════════════════════════════════════════════

const FEW_SHOT_CONTRAST_EXEMPLARS = `
## FEW-SHOT CALIBRATION EXEMPLARS (CONTRASTING POOR VS HIGH-YIELD FORMULATION)

### Raw Medical Slide Excerpt:
"Slide 14: Heart Failure Pharmacotherapy
- Beta-Blockers (Carvedilol, Metoprolol Succinate, Bisoprolol)
- Proven mortality benefit in HFrEF
- Must start at low dose; can temporarily worsen decompensation
- Mechanism: Decreases chronic sympathetic overactivation, prevents remodeling"

### POOR GENERATION (COMPOSITE / PARAGRAPH TRAP ANTI-PATTERN - DO NOT DO THIS):
{
  "front": "What are the beta-blockers used in heart failure, what do they do, and what are their side effects?",
  "back": "Carvedilol, Metoprolol Succinate, and Bisoprolol. They have a proven mortality benefit in HFrEF. They must start at low doses because they can cause temporary decompensation. They decrease sympathetic overactivation and prevent remodeling."
}
*Flaws: Combines 3 drug names, indications, dosing cautions, and 2 distinct mechanisms into 1 card. Violates Minimum Information Principle, causes partial recall and frequent card lapses (leeches).*

### OPTIMAL GENERATION (HIGH-YIELD ATOMIC DECOMPOSITION ACROSS BLOOM'S TAXONOMY):
[
  {
    "bloom_level": "Remembering",
    "card_type": "Basic_QA",
    "conceptual_lens": "Attributes",
    "front": "Which three specific beta-blockers have demonstrated proven mortality reduction in heart failure with reduced ejection fraction (HFrEF)?",
    "back": "Carvedilol, Metoprolol Succinate, and Bisoprolol.",
    "pedagogical_rationale": "Tests the specific clinical trio of evidence-based agents without extraneous pharmacology."
  },
  {
    "bloom_level": "Understanding",
    "card_type": "Basic_QA",
    "conceptual_lens": "Causes_Effects",
    "front": "Why must beta-blocker therapy in stable HFrEF patients be initiated at very low doses and titrated slowly?",
    "back": "To prevent transient hemodynamic deterioration from acute withdrawal of adrenergic compensatory support.",
    "pedagogical_rationale": "Focuses exclusively on the physiological mechanism of drug titration."
  },
  {
    "bloom_level": "Understanding",
    "card_type": "Basic_QA",
    "conceptual_lens": "Causes_Effects",
    "front": "What long-term cardiac structural process is attenuated by beta-blocker suppression of sympathetic overactivation in HFrEF?",
    "back": "Adverse ventricular remodeling (myocyte hypertrophy and interstitial fibrosis).",
    "pedagogical_rationale": "Isolates the downstream structural pathophysiology targeted by therapy."
  },
  {
    "bloom_level": "Applying",
    "card_type": "Two_Step_Vignette",
    "conceptual_lens": "Implications",
    "front": "A 62-year-old male with stable HFrEF ($EF = 30\\%$) on an ACE inhibitor is prescribed carvedilol. Beyond beta-1 blockade, what additional receptor antagonism contributes to carvedilol's clinical effect?",
    "back": "Alpha-1 adrenergic receptor blockade, providing peripheral vasodilation and afterload reduction.",
    "pedagogical_rationale": "Requires the learner to recall carvedilol's specific drug class and retrieve its secondary pharmacodynamic property."
  }
]
`

// ═══════════════════════════════════════════════════════════════════════════════
// BASIC CARD GENERATION & EVALUATION PROMPTS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Build a high-yield card generation prompt grounded in the C.R.E.A.T.E. framework
 */
export function buildCardGenerationPrompt(
  extractedText: string,
  minCards: number = 10,
  minQuestions: number = 5
): string {
  return `You are an expert cognitive scientist, psychometrician, and instructional designer specializing in retrieval practice and spaced repetition system (SRS) design.
Your mission is to transform the provided source material into exceptionally high-yield, atomic active recall items adhering strictly to Piotr Wozniak's Minimum Information Principle and Andy Matuschak's prompt formulation heuristics.

<source_material>
${extractedText}
</source_material>

## CORE OPERATIONAL DIRECTIVES (C.R.E.A.T.E. FRAMEWORK):

1. **ATOMICITY & MINIMUM INFORMATION PRINCIPLE (ONE INFERENTIAL STEP)**:
   - Each flashcard must test exactly ONE discrete fact, concept, or mechanism.
   - If a concept has multiple parts, split it into separate cards. Never create composite cards or multi-item lists.
   - If an answer requires more than one distinct proposition or contains the conjunction "and", decompose it into distinct cards.

2. **PRECISE & UNAMBIGUOUS HORIZONS**:
   - The question must clearly signal what category and shape of answer is expected (mechanism, physiological outcome, mathematical definition, anatomical landmark).
   - Prepend a domain context cue in brackets when helpful (e.g., "[Cardiology: Anatomy]", "[Macroeconomics]").

3. **SPOILER-FREE PROMPT FRAMING**:
   - Never reveal the answer, association, or mechanism within the question itself.
   - PROHIBITED: "Why does mutation X cause phenotype Y?" (Tells the learner that X causes Y).
   - REQUIRED: "What phenotypic abnormality is produced by mutation X?" followed by "By what mechanism does mutation X produce phenotype Y?"

4. **STRICT PROHIBITION OF LOW-EFFORT FORMATS**:
   - NEVER generate binary (Yes/No, True/False) questions.
   - NEVER generate unranked list/enumeration prompts ("List the 5 symptoms of...").
   - NEVER create dense card backs. The answer field must be restricted to the direct target term, value, or concise explanatory phrase (<15 words, spoken in a single breath).

5. **COGNITIVE BREADTH (BLOOM'S TAXONOMY DISTRIBUTION)**:
   - ~40% Levels 1 & 2: Remembering & Understanding (definitions, core facts, mechanisms).
   - ~40% Level 3: Applying (two-step reasoning vignettes: "Under conditions of X, what is the consequence for Y?").
   - ~20% Level 4: Analyzing (differential analysis: "How does A differ from B regarding mechanism C?").

6. **MATHEMATICAL & SCIENTIFIC FORMATTING (LaTeX)**:
   - Wrap all mathematical expressions, formulas, variables, and scientific notation in standard LaTeX ($...$ for inline, $$...$$ for block formulas, e.g. $x^3$, $a^2 + b^2 = c^2$, $\\text{H}_2\\text{O}$).

7. **INTERACTIVE GRAPHS & VISUALIZATIONS (Vega-Lite)**:
   - For complex multi-variable models (e.g., equilibrium shifts in economics, phase portraits in physics, compounding growth), you may include an interactive \`\`\`vega-lite JSON block.
   - **Interactive Parameter Curves**: When using interactive sliders (\`params\` with \`bind: { input: "range", min: ..., max: ..., step: ... }\`), NEVER use hardcoded static points. You MUST generate a domain sequence via \`data: { sequence: { start: 0, stop: N, step: S, as: "x" } }\` and compute curves dynamically via \`transform: [{ calculate: "...", as: "y" }]\`.
   - **Vega Expression Syntax**: Use \`pow(base, exp)\` instead of \`^\` (e.g. \`C0 * pow(1 + r, datum.t)\`).
   - **Frequency Guardrail**: Do NOT overuse charts. Only synthesize a graph when spatial, comparative, or multi-curve modeling is essential.

8. **STRICT SOURCE GROUNDING (ZERO HALLUCINATIONS)**:
   - All items MUST be extracted strictly and exclusively from the <source_material>. Do NOT introduce outside facts or assumed concepts.

Generate exactly ${minCards} flashcards and exactly ${minQuestions} active recall questions.

OUTPUT FORMAT REQUIREMENTS:
Return valid JSON matching this exact structure (no markdown fences, no conversational prose):
{
  "flashcards": [
    {
      "front": "Clear, precise, atomic question or cloze prompt",
      "back": "Concise, definitive answer (<15 words)",
      "concept": "Major overarching topic name"
    }
  ],
  "active_recall": [
    {
      "question": "Deep conceptual inquiry starting with Why/How/Explain the mechanism of... or 2-step vignette",
      "model_answer": "Complete, structured explanation with key conceptual checkpoints",
      "concept": "Major overarching topic name"
    }
  ]
}`
}

/**
 * Build an advanced answer evaluation prompt grounded in Retrieval Practice & Misconception Diagnostics
 */
export function buildEvaluationPrompt(
  question: string,
  modelAnswer: string,
  studentAnswer: string
): string {
  return `You are an expert cognitive learning scientist and diagnostic psychometrician grading a student's active recall response.

QUESTION: ${question}
MODEL ANSWER: ${modelAnswer}
STUDENT ANSWER: ${studentAnswer}

Evaluate the student's retrieval attempt and respond in JSON:
{
  "key_points_analyzed": [
    { "point": "Atomic fact or mechanistic criterion from model answer", "status": "recalled | partially_recalled | missed" }
  ],
  "contradictions_or_misconceptions": "Identify any factual inversions, broken causal links, or state 'None'.",
  "feedback": "Specific, encouraging, and constructive feedback. Acknowledge what was accurately retrieved, identify missing criteria, and provide a brief Socratic hint for any misconception.",
  "score": 0-5,
  "correct": true or false
}

GRADING CRITERIA & DIAGNOSTIC RULES:
1. Deconstruct the model answer into 1-3 atomic key points and assess coverage.
2. POLARITY & CONTRADICTION VETO: If the student asserts a direct factual contradiction, inverted cause-effect relationship, or fundamental misconception, score MUST be capped at 1 and correct MUST be false, even if peripheral keywords match.
3. FLEXIBLE SEMANTIC & LOGICAL EVALUATION:
   - Capture of the core concept, mechanism, or underlying meaning in the student's own words counts as 'recalled'.
   - If the student's answer logically entails or implies the model answer (e.g. stating that 'all coordinates changed/shifted' implies 'the line/curve moved'; or describing the exact causal mechanism without a rigid buzzword), count it as fully recalled and correct.
   - Never mark an answer wrong purely due to alternative phrasing or informal terminology if the conceptual understanding is sound.
4. Partial credit (score 3) if key points are partially recalled without major errors.
5. Score scale:
   - 5 = Full, accurate recall of core concepts and mechanisms.
   - 3-4 = Partial recall with minor omissions but sound logic.
   - 1-2 = Significant errors, inverted mechanisms, or major omissions.
   - 0 = Blank or completely irrelevant response.
6. Order your thought process: analyze key points and misconceptions FIRST, then write feedback, and determine the score LAST.
7. Wrap mathematical expressions in LaTeX delimiters ($...$).

Return ONLY valid JSON.`
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENHANCED UNIFIED CARD GENERATION PROMPTS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Build an enhanced card generation prompt incorporating Andy Matuschak's 5 Conceptual Lenses,
 * Bloom's Taxonomy, and strict psychometric constraints.
 */
export function buildAutoCardGenerationPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  topicTitle?: string,
  existingCards?: { front: string; back?: string }[],
  minCards: number = 8,
  minQuestions: number = 4,
  availableTopics?: string[],
  autoCount: boolean = false
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`
  if (topicTitle) contextSection += `\nTOPIC: ${topicTitle}`
  if (availableTopics && availableTopics.length > 0) {
    contextSection += `\n\n## 🏷️ CANONICAL TOPICS (STRICT REQUIREMENT)\nAssign each generated card's "concept" field to one of these cohesive major topics (do NOT create new one-off micro-topics):\n${availableTopics.map(t => `- "${t}"`).join('\n')}`
  }

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any concepts, questions, or terms already covered in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
If a topic is already covered above, find fresh angles, deeper mechanisms, distinct applications, or unaddressed subtopics.`
  }

  return `You are a world-class cognitive scientist, psychometrician, and instructional designer specializing in retrieval practice and spaced repetition system (SRS) design.
Your mission is to transform the provided source material into exceptionally high-yield, atomic active recall items adhering strictly to Piotr Wozniak's Minimum Information Principle and Andy Matuschak's prompt formulation heuristics.

CONTEXT:${contextSection}

<source_material>
${extractedText}
</source_material>

## COGNITIVE SCIENCE CARD DESIGN PRINCIPLES (MUST FOLLOW):

1. **MINIMUM INFORMATION PRINCIPLE (ATOMICITY / ONE INFERENTIAL STEP)**:
   - Each flashcard must isolate and test EXACTLY ONE atomic unit of knowledge.
   - NEVER bundle multiple facts, sequential lists, or compound mechanisms into a single card.
   - If a concept has three components, construct three independent, atomic cards.

2. **MATUSCHAK'S 5 CONCEPTUAL LENSES**:
   - Deconstruct abstract concepts across the five lenses:
     - **Attributes**: What defines the invariant properties and tendencies of the concept?
     - **Differences (Discrimination)**: How does it contrast against adjacent/confusable concepts?
     - **Parts_Wholes**: Structural decompositions, taxonomic hierarchies, and systems.
     - **Causes_Effects**: Functional mechanisms, triggers, and downstream consequences.
     - **Implications**: Why the concept matters, boundary conditions, and real-world transfer.

3. **COGNITIVE BREADTH (BLOOM'S TAXONOMY 40/40/20 DISTRIBUTION)**:
   - **40% Levels 1 & 2 (Remembering & Understanding)**: Precise recall of key facts, terminology, and causal mechanisms.
   - **40% Level 3 (Applying)**: Applied scenarios (e.g., two-step reasoning vignettes: "Under conditions of X, what is the consequence for Y?").
   - **20% Level 4 (Analyzing)**: Relational and differential analysis ("How does A differ from B regarding mechanism C?").

4. **SPOILER-FREE PROMPT FRAMING**:
   - Never reveal the target association, diagnosis, or mechanism within the question.
   - PROHIBITED: "Why does factor X cause condition Y?" (Reveals that X causes Y).
   - REQUIRED: "What condition is produced by factor X?" followed by "By what mechanism does factor X lead to condition Y?"

5. **ANSWER CONCISENESS (<15 WORDS / SINGLE BREATH)**:
   - The "back" field of flashcards must contain ONLY the direct target fact, term, value, or single explanatory phrase (<15 words).
   - Deep rationale, context, or clinical significance must be placed in the "pedagogical_rationale" field.

6. **STRICT PROHIBITION OF LOW-EFFORT FORMATS & LOGISTICS**:
   - NEVER generate binary (Yes/No, True/False) prompts.
   - NEVER create unranked list/enumeration cards ("List the 4 types of...").
   - Absolutely NEVER generate cards for course logistics, homework deadlines, exam dates, syllabus rules, or textbook chapter timelines.
   - Discard all conversational tangents, professor jokes, and classroom management banter.

7. **MATHEMATICAL & SCIENTIFIC NOTATION (LaTeX)**:
   - Wrap all mathematical equations, variables, exponents, and chemical/scientific notation in standard LaTeX delimiters ($...$ for inline or $$...$$ for block formulas, e.g. $x^3$, $a^2 + b^2 = c^2$, $\\text{H}_2\\text{O}$).

8. **INTERACTIVE GRAPHS (Vega-Lite)**:
   - In active recall explanations or visual conceptual items (e.g. market equilibrium shifts, IS-LM, phase transitions), you may embed an interactive \`\`\`vega-lite block. Use sparingly and only when necessary for multi-variable models.

9. **ZERO-DEFECT TABULAR STRUCTURES & NEUROSYMBOLIC VERIFICATION**:
   - When extracting from tables, schedules, balance sheets, or multi-column data:
     - Preserve complete grid coordinates and Cartesian path tuples (e.g. ["Segment", "Year", "Metric"]).
     - Enforce vertical footing sums (\\sum \\text{detail rows} = \\text{total}) and horizontal cross-footing without hallucinated math.
     - For econometric tables, point estimates must be accompanied by clustered standard errors in parentheses directly below coefficients and academic significance markers ($^*p < 0.10, ^{**}p < 0.05, ^{***}p < 0.01$).
     - You may format tabular summaries using clean Markdown pipe tables.

10. **STRICT SOURCE GROUNDING (NOTEBOOKLM MODE - ZERO HALLUCINATIONS)**:
    - Every single flashcard and active recall question MUST be strictly and exclusively grounded in the <source_material>.
    - Absolutely NO hallucinations, external facts, or assumed knowledge not present in the text.
${FEW_SHOT_CONTRAST_EXEMPLARS}
## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "flashcards": [
    {
      "front": "Clear, precise, atomic question or cloze prompt",
      "back": "Concise, definitive answer (<15 words)",
      "concept": "Major overarching theme (Group cards under 3-5 broad themes across the deck)",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential | Image_Occlusion | Cloze",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification explaining why this prompt targets a high-yield concept",
      "concrete_example": "A concrete real-world scenario or analogy illustrating this concept",
      "common_mistake": "A frequent student misconception or trap to avoid",
      "mnemonic": "An intuitive memory hook, acronym, or vivid mental visual",
      "checkpoints": ["Key idea 1 student must recall", "Key idea 2 student must recall"]
    }
  ],
  "active_recall": [
    {
      "question": "Deep conceptual inquiry starting with Why/How/Explain the mechanism of... or scenario analysis",
      "model_answer": "Complete, structured explanation with key conceptual checkpoints for mastery",
      "concept": "Major overarching theme (Must match one of the 3-5 broad themes across the deck)",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification explaining why this prompt targets a high-yield concept",
      "concrete_example": "A real-world application or case study",
      "common_mistake": "A common reasoning flaw or incorrect assumption",
      "mnemonic": "Optional memory aid or mental framework",
      "checkpoints": ["Key conceptual criterion 1", "Key conceptual criterion 2"]
    }
  ]
}

## GENERATION TARGETS
${autoCount
  ? `- Automatically evaluate the depth, density, and breadth of the source material to determine the optimal number of flashcards and active recall questions needed for comprehensive conceptual coverage without fluff or redundancy (e.g. 4-8 cards for brief material, 12-18 cards for standard lectures, strictly capped at 20-25 cards max for very dense material).
- Cover every key definition, mechanism, rule, and distinction without padding or omitting essentials.`
  : `- Generate exactly ${minCards} flashcards and ${minQuestions} active recall questions.
- Distribute evenly across all major concepts in the source material.`}${dedupSection}

Return ONLY valid JSON. No markdown fences. No preamble.`
}

/**
 * Build a prompt requesting flashcards ONLY (no active recall).
 */
export function buildFlashcardOnlyPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  minCards: number = 10,
  existingCards?: { front: string; back?: string }[],
  availableTopics?: string[],
  autoCount: boolean = false
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`
  if (availableTopics && availableTopics.length > 0) {
    contextSection += `\n\n## 🏷️ CANONICAL TOPICS (STRICT REQUIREMENT)\nAssign each generated card's "concept" field to one of these cohesive major topics (do NOT create new one-off micro-topics):\n${availableTopics.map(t => `- "${t}"`).join('\n')}`
  }

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any concepts, questions, or terms already covered in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
Generate cards strictly for new, unaddressed terms and subconcepts.`
  }

  return `You are a world-class cognitive scientist, psychometrician, and instructional designer specializing in retrieval practice and spaced repetition system (SRS) design.
Your mission is to generate high-yield, atomic flashcards engineered for spaced repetition and rapid semantic retrieval.

CONTEXT:${contextSection}

<source_material>
${extractedText}
</source_material>

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "flashcards": [
    {
      "front": "Atomic prompt or cloze deletion (e.g. 'Photosynthesis is the process by which ___')",
      "back": "Concise, definitive answer (<15 words, speakable in a single breath)",
      "concept": "Major topic name (Group cards under 3-5 broad overarching themes across the deck)",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential | Cloze",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification explaining why this prompt targets a high-yield concept",
      "concrete_example": "A concrete real-world scenario or analogy illustrating this concept",
      "common_mistake": "A frequent student misconception or trap to avoid",
      "mnemonic": "An intuitive memory hook, acronym, or vivid mental visual",
      "checkpoints": ["Key idea 1 student must recall", "Key idea 2 student must recall"]
    }
  ]
}

## FLASHCARD DESIGN RULES (MUST FOLLOW)

1. **Minimum Information Principle (Atomicity)**:
   - Each card tests EXACTLY ONE indivisible relationship, term, or mechanism.
   - Absolutely NO compound lists, multi-part enumerations, or dense paragraphs on the back.
   - Restrict the back to <15 words; move supporting context to "pedagogical_rationale".

2. **Spoiler-Free Prompt Framing**:
   - Never reveal the target association, diagnosis, or mechanism in the prompt.
   - Do NOT ask binary (Yes/No, True/False) questions.

3. **Matuschak's 5 Conceptual Lenses**:
   - Distribute cards across Attributes, Differences, Parts_Wholes, Causes_Effects, and Implications.

4. **Strict Exclusion of Logistics & Conversational Banter (CRITICAL)**:
   - Absolutely NEVER generate cards for course mechanics, syllabus details, exam schedules, homework deadlines, or textbook chapter timelines.
   - Discard all conversational tangents, professor jokes, and classroom management banter.

5. **LaTeX Mathematical Formatting**:
   - Wrap all equations, formulas, variables, exponents, and chemical expressions in LaTeX delimiters ($...$ or $$...$$).

6. ${autoCount
  ? `**Dynamic Card Count (CRITICAL)**: Automatically determine the optimal number of flashcards needed to comprehensively cover the material without fluff, trivia, or redundancy. Analyze the material's depth and breadth: generate as few as 3-5 cards if the material is brief or focused, or as many as needed (typically 8-16 cards for standard lectures, strictly capped at 20 cards max for deeper material) to ensure complete conceptual coverage. Do NOT artificially pad with trivial cards, and do NOT truncate important concepts.`
  : `**Generate exactly ${minCards} flashcards** (do not generate more or fewer) — Cover all distinct concepts, definitions, and mechanisms evenly.`}

7. **NO active recall questions.** Flashcards only.

8. **Strict Source Grounding (NotebookLM Mode - ZERO HALLUCINATIONS)**:
   - Flashcards MUST be strictly and exclusively derived from the <source_material> above.
   - Do NOT hallucinate or bring in external concepts from pre-trained knowledge.${dedupSection}

Return ONLY valid JSON. No markdown fences. No commentary.`
}

/**
 * Build a prompt requesting active recall questions ONLY (no flashcards).
 */
export function buildActiveRecallOnlyPrompt(
  extractedText: string,
  subjectName?: string,
  moduleTitle?: string,
  minQuestions: number = 6,
  existingCards?: { front: string; back?: string }[],
  availableTopics?: string[],
  autoCount: boolean = false
): string {
  let contextSection = ''
  if (subjectName) contextSection += `\nSUBJECT: ${subjectName}`
  if (moduleTitle) contextSection += `\nMODULE: ${moduleTitle}`
  if (availableTopics && availableTopics.length > 0) {
    contextSection += `\n\n## 🏷️ CANONICAL TOPICS (STRICT REQUIREMENT)\nAssign each generated card's "concept" field to one of these cohesive major topics (do NOT create new one-off micro-topics):\n${availableTopics.map(t => `- "${t}"`).join('\n')}`
  }

  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any questions or scenarios already present in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
Generate novel questions exploring unaddressed mechanisms, deeper edge cases, or distinct applications.`
  }

  return `You are a world-class cognitive scientist, psychometrician, and instructional designer specializing in retrieval practice and active recall system design.
Your mission is to generate high-yield active recall questions designed for elaborative interrogation, causal reasoning, and deep conceptual mastery.

CONTEXT:${contextSection}

<source_material>
${extractedText}
</source_material>

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "active_recall": [
    {
      "question": "Open-ended inquiry requiring deep conceptual understanding (Why/How/Explain/Compare/Analyze)",
      "model_answer": "Complete, rigorous model answer highlighting the core conceptual criteria",
      "concept": "Major topic name (Group cards under 3-5 broad overarching themes across the deck)",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification explaining why this prompt targets a high-yield concept",
      "concrete_example": "A real-world application, case study, or problem scenario",
      "common_mistake": "A common logical flaw, incomplete explanation, or misconception",
      "mnemonic": "Optional mental framework or memory aid",
      "checkpoints": ["Key conceptual criterion 1", "Key conceptual criterion 2"]
    }
  ]
}

## ACTIVE RECALL QUESTION DESIGN RULES (MUST FOLLOW)

1. **Elaborative Interrogation & Causal Reasoning**:
   - Questions must demand deep causal explanation ("Why does glycolysis lead to pyruvate production?", "How does ATP synthase produce energy?").
   - Avoid shallow factual lookups or simple single-word answers.
   - Do NOT ask binary (Yes/No, True/False) questions or unranked list enumerations ("List 5 types...").

2. **Scenario Application & 2-Step Vignettes (Bloom Level 3)**:
   - Include 2-step clinical or engineering vignettes: "A patient presents with symptoms X after receiving drug Y. What downstream enzyme is inhibited and why?"

3. **Concept Discrimination & Boundary Testing (Bloom Level 4)**:
   - For confusable concepts, construct explicit boundary-testing comparison questions: "How does Mitosis differ from Meiosis in terms of genetic variation?"

4. **Spoiler-Free Question Framing**:
   - Never reveal the core causal mechanism or outcome within the question stem itself.

5. **Rigorous Model Answers**:
   - Provide clear, comprehensive model answers with the key checkpoints needed for self-grading or AI evaluation.

6. ${autoCount
  ? `**Dynamic Question Count (CRITICAL)**: Automatically determine the optimal number of active recall questions needed to comprehensively cover the core mechanisms, causal relationships, and reasoning without redundancy. Generate as few as 2-4 questions for brief material, or 4-6 for standard lectures, strictly capped at 8 max for deep material. Every question must test a distinct, high-impact concept.`
  : `**Generate exactly ${minQuestions} active recall questions** (do not generate more or fewer) — Covering all major topics in depth.`}

7. **NO flashcards.** Active recall questions only.

8. **Strict Source Grounding (NotebookLM Mode - ZERO HALLUCINATIONS)**:
   - Questions and model answers MUST be derived exclusively from the <source_material> above.
   - Never introduce outside concepts or unmentioned theories.${dedupSection}

Return ONLY valid JSON. No markdown fences. No commentary.`
}

// ═══════════════════════════════════════════════════════════════════════════════
// MODALITY-SPECIFIC KNOWLEDGE EXTRACTION PROMPT BUILDERS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Specialized PowerPoint Slide Deck Knowledge Extractor.
 * Restores causal links from telegraphic bullets, decouples nested points,
 * and formats multi-node diagrams for sequential pathway analysis.
 */
export function buildSlideDeckCardGenerationPrompt(
  slideText: string,
  subjectName: string,
  deckTitle?: string,
  targetCards: number = 12
): string {
  return `You are a Senior Cognitive Systems Engineer and Psychometric Assessment Specialist specializing in lecture slide extraction.
Analyze the provided slide deck text and transform it into high-yield, atomic flashcards and active recall items.

=SOURCE MODALITY: POWERPOINT PRESENTATION SLIDES=
Subject: ${subjectName}
${deckTitle ? `Slide Deck Title: ${deckTitle}` : ''}

<source_material>
${slideText}
</source_material>

## THREE-PHASE SLIDE DECONSTRUCTION PROTOCOL:
1. **Reconstruct Implicit Causal Prose**:
   - Presentation slides condense text into telegraphic bullets and fragmented phrases. Re-establish their implied causal connections before breaking them into atomic cards.
2. **Decouple Nested Bullet Points**:
   - When a slide lists diagnostic signs, biomarker criteria, or therapeutic options under a single header, treat EACH bullet as a standalone cognitive link rather than an omnibus list.
3. **Sequential Pathway & Vignette Transformation**:
   - For sequential biochemical, physical, or physiological pathways, test step-by-step causal predecessor/successor relationships.
   - Convert passive bullet assertions into two-step applied clinical or engineering vignettes where appropriate.

## PEDAGOGICAL CONSTRAINTS (STRICT):
- Minimum Information Principle: Each card tests EXACTLY ONE atomic fact or mechanism.
- Answer Conciseness: Back field strictly <15 words (single breath). Put extended explanations in "pedagogical_rationale".
- Prohibition of Anti-Patterns: NO binary (Yes/No) questions, NO unranked lists ("List the 4 types..."), NO spoiler prompts.
- LaTeX Math: Format all equations/variables in LaTeX ($...$).
- Zero Hallucinations: Ground strictly in the <source_material>.

Target Card Count: Approximately ${targetCards} total items (balanced mix of atomic flashcards and 2-step vignettes).

OUTPUT FORMAT: Return ONLY valid JSON matching this schema:
{
  "flashcards": [
    {
      "front": "Clear, precise, atomic question (with domain context tag e.g. '[Cardiology: Anatomy]')",
      "back": "Concise, definitive answer (<15 words)",
      "concept": "Major overarching theme",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification of clinical/academic significance"
    }
  ],
  "active_recall": [
    {
      "question": "Deep inquiry testing causal mechanism or two-step scenario",
      "model_answer": "Complete, structured model answer",
      "concept": "Major overarching theme",
      "card_type": "Two_Step_Vignette | Differential",
      "bloom_level": "Applying | Analyzing",
      "pedagogical_rationale": "One-line justification"
    }
  ]
}`
}

/**
 * Specialized Textbook and Primary Literature Knowledge Extractor.
 * Implements macro-comprehension read, strips authorial fluff, and applies
 * Andy Matuschak's 5 conceptual lenses to deconstruct dense academic prose.
 */
export function buildTextbookCardGenerationPrompt(
  textbookText: string,
  subjectName: string,
  chapterTitle?: string,
  targetCards: number = 15
): string {
  return `You are a Senior Cognitive Systems Engineer and Psychometric Assessment Specialist specializing in academic literature extraction.
Analyze the provided textbook chapter/section and formulate high-yield, atomic retrieval practice prompts.

=SOURCE MODALITY: TEXTBOOK CHAPTER / SECTION=
Subject: ${subjectName}
${chapterTitle ? `Chapter/Section: ${chapterTitle}` : ''}

<source_material>
${textbookText}
</source_material>

## THREE-PHASE TEXTBOOK EXTRACTION PROTOCOL:
1. **Macro-Comprehension & Schema Mapping**:
   - Identify the overarching conceptual schema and hierarchical taxonomy before processing fine details.
2. **Deconstruct Definitions via Matuschak's 5 Conceptual Lenses**:
   - NEVER copy lengthy textbook definitions verbatim onto the back of cards.
   - Deconstruct definitions across:
     - *Attributes*: What defines the concept?
     - *Differences*: How does it contrast with adjacent concepts?
     - *Causes & Effects*: What are the functional mechanisms and downstream results?
     - *Parts & Wholes*: What structural decomposition applies?
     - *Implications*: How does the principle apply to novel problem scenarios?
3. **Strip Fluff & Enforce Atomicity**:
   - Strip out authorial transitions, historical background, and redundant narrative examples.
   - Isolate core factual assertions into standalone, atomic retrieval prompts.

## PEDAGOGICAL CONSTRAINTS (STRICT):
- Minimum Information Principle: 1 indivisible cognitive step per card.
- Answer Conciseness: Back field strictly <15 words. Place extended context in "pedagogical_rationale".
- Anti-Pattern Prohibitions: NO Yes/No questions, NO list memorization, NO spoiler prompts.
- LaTeX Math: Wrap all equations in $...$ or $$...$$.
- Strict Grounding: Ground exclusively in <source_material>.

Target Card Count: Approximately ${targetCards} items.

OUTPUT FORMAT: Return ONLY valid JSON:
{
  "flashcards": [
    {
      "front": "Specific, unambiguous prompt (with domain tag)",
      "back": "Direct, minimal answer containing only the core target fact (<15 words)",
      "concept": "Major overarching theme",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "Brief note on why this concept was selected"
    }
  ],
  "active_recall": [
    {
      "question": "Causal mechanism inquiry or differential comparison prompt",
      "model_answer": "Complete, rigorous model answer",
      "concept": "Major overarching theme",
      "conceptual_lens": "Causes_Effects | Differences | Implications",
      "bloom_level": "Understanding | Applying | Analyzing",
      "pedagogical_rationale": "Mechanistic significance"
    }
  ]
}`
}

/**
 * Specialized Spoken Lecture Audio and Transcript Knowledge Extractor.
 * Normalizes speech, strips conversational filler, detects instructor emphasis cues,
 * resolves deictic pronouns, and includes timestamp attribution.
 */
export function buildTranscriptCardGenerationPrompt(
  transcriptText: string,
  subjectName: string,
  lectureTitle?: string,
  targetCards: number = 12
): string {
  return `You are a Cognitive Systems Specialist analyzing a raw, spoken lecture transcript to formulate high-retrieval spaced practice prompts.

=SOURCE MODALITY: SPOKEN LECTURE TRANSCRIPT=
Subject: ${subjectName}
${lectureTitle ? `Lecture: ${lectureTitle}` : ''}

<source_material>
${transcriptText}
</source_material>

## THREE-PHASE TRANSCRIPT PARSING PROTOCOL:
1. **Filtering & Normalization**:
   - Strip away all conversational filler words ("um", "like", "you know"), rhetorical digressions, classroom pleasantries, administrative announcements, and syntactically incomplete statements.
   - Reconstruct fragmented spoken remarks into grammatically complete, self-contained propositional statements.
2. **Instructor Emphasis Identification**:
   - Scan specifically for verbal markers of pedagogical emphasis (e.g. "This distinction is critical", "Students always confuse this", "This will appear on exams", "Be sure not to confuse X with Y", "The common trap is").
   - Prioritize these emphasized concepts for card generation.
3. **Deictic Ambiguity Resolution**:
   - Identify and replace all deictic pronouns and gestures ("this", "that thing on the slide", "here", "as you see here") with explicit, standardized academic terminology.

## PEDAGOGICAL CONSTRAINTS (STRICT):
- Minimum Information Principle: Each card tests 1 single atomic proposition.
- Answer Conciseness: Back field strictly <15 words.
- Anti-Pattern Prohibitions: NO binary questions, NO unranked lists, NO spoiler prompts.
- Timestamp Attribution: Include timestamp or lecture cue in "source_marker" when available.
- LaTeX Math: Wrap all formulas in LaTeX ($...$).

Target Card Count: Approximately ${targetCards} items.

OUTPUT FORMAT: Return ONLY valid JSON:
{
  "flashcards": [
    {
      "front": "Clear question targeting the emphasized concept",
      "back": "Precise, unambiguous target answer (<15 words)",
      "concept": "Major overarching theme",
      "emphasis_marker_detected": "Verbatim phrase where instructor emphasized this topic (or 'None')",
      "source_marker": "Timestamp e.g., '14:22' or specific lecture cue if available",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "Explanation of relevance to exams or clinical/academic practice"
    }
  ],
  "active_recall": [
    {
      "question": "Deep inquiry addressing common student misconceptions or mechanisms emphasized by instructor",
      "model_answer": "Complete, structured model answer",
      "concept": "Major overarching theme",
      "emphasis_marker_detected": "Verbatim phrase of instructor emphasis (or 'None')",
      "source_marker": "Timestamp or lecture marker",
      "bloom_level": "Understanding | Applying | Analyzing",
      "pedagogical_rationale": "Explanation of relevance"
    }
  ]
}`
}

/**
 * Build a structured lecture notes prompt that converts raw transcript into
 * a rich Markdown document optimized for Neuron's AI card generator, curriculum builder,
 * and AI Tutor.
 */
export function buildLectureNotesPrompt(
  rawTranscript: string,
  subjectName: string,
  lectureTitle: string
): string {
  return `You are an elite academic tutor and cognitive instructional designer creating comprehensive, beautifully structured study notes from a lecture recording for the class "${subjectName}".

LECTURE TITLE: ${lectureTitle}
CLASS: ${subjectName}

<source_material>
${rawTranscript}
</source_material>

## TRANSCRIPT NORMALIZATION & SYNTHESIS DIRECTIVES:
1. **Strip Conversational Noise**: Filter out vocal fillers, administrative announcements, classroom banter, and false starts.
2. **Deictic Resolution**: Convert spoken pointers ("this", "that graph", "over here") into explicit academic terms.
3. **Flag Pedagogical Emphasis**: Highlight concepts where the instructor used rhetorical emphasis ("This distinction is critical", "Common exam trap", "Don't confuse X with Y").

Generate a comprehensive, structured Markdown study document based on this lecture.
Requirements:
1. Use GitHub-flavored Markdown.
2. Structure the document with these exact sections:
   # 📚 ${subjectName}: ${lectureTitle}

   ## 🎯 Executive Summary & Objectives
   A high-level synthesis of what this lecture was about, key themes, and main takeaways.

   ## 🔑 Key Concepts, Definitions & Formulas
   Bulleted list of every important term, concept, definition, equation, or theorem introduced in the lecture. Format each as:
   - **Term / Concept**: Definition, context, and significance (wrap math in LaTeX $...$).

   ## ⏱️ Detailed Chronological Notes
   Organized by major topic or time block (e.g. ### [00:00 - 25:00] Topic Name). Provide thorough, structured notes with explanations, bullet points, and examples given in the lecture.

   ## 💡 Potential Exam Questions & Review Points
   5-10 active recall questions that test understanding of core mechanisms and applications from this lecture (following Bloom's Taxonomy).

   <details>
   <summary>📜 Click to expand full raw transcript</summary>

   ${rawTranscript}

   </details>

3. Do NOT wrap the entire output in triple backtick fences. Output clean, raw Markdown directly.
4. Strict Grounding (NotebookLM Mode - ZERO HALLUCINATIONS): Base all notes strictly and exclusively on the provided <source_material>.`
}

/**
 * Build a multi-source triangulation card generation prompt that synthesizes
 * across multiple course materials (slides, textbook, lecture transcript)
 * without chunking, cross-referencing and unifying concepts.
 */
export function buildMultiSourceCardGenerationPrompt(
  sourcesText: string,
  subjectName: string,
  sourceFilenames: string[],
  existingCards?: { front: string; back?: string }[],
  targetFlashcards: number = 14,
  targetActiveRecall: number = 4
): string {
  let dedupSection = ''
  if (existingCards && existingCards.length > 0) {
    dedupSection = `\n\n## ⚠️ DEDUPLICATION REQUIREMENT (CRITICAL)
Do NOT duplicate or re-test any concepts, questions, or terms already covered in the existing deck:
${existingCards.slice(0, 40).map(c => `- "${c.front}"`).join('\n')}
If a topic is already covered above, find fresh angles, deeper mechanisms, distinct applications, or unaddressed subtopics.`
  }

  return `You are a world-class cognitive scientist, psychometrician, and learning engineer.
You have been provided with MULTIPLE distinct learning materials for the subject "${subjectName}":
${sourceFilenames.map((f, i) => `${i + 1}. ${f}`).join('\n')}

Your mission is to perform MULTI-SOURCE SYNTHESIS AND TRIANGULATION across these materials to produce an elite, high-yield deck of atomic flashcards and active recall questions optimized for spaced repetition and deep semantic retention.

## 🎯 TRIANGULATION DIRECTIVE (READ CAREFULLY)
You are reading all source documents end-to-end. Do NOT treat each document in isolation. Instead:
1. **Triangulate Core Concepts**: Identify concepts that appear across multiple sources (e.g. introduced in slides, deeply explained in the textbook, and discussed with verbal examples in the lecture transcript).
2. **Synthesize Complementary Perspectives**:
   - Draw precise mathematical rigor, formal definitions, and mechanisms from the textbook.
   - Draw core structural hierarchies, emphasis, and key term priorities from the slides.
   - Draw intuition, vivid analogies, practical examples, and clarification of common student pitfalls from the lecture transcript.
3. **Unify & Deduplicate Across Sources**: NEVER produce separate cards for the same concept from different documents. Combine insights into a single definitive, atomic card.
4. **Minimum Information Principle**: Every single flashcard MUST isolate exactly ONE atomic fact, concept, or relationship (<15 words on back).
5. **Bloom's Taxonomy 40/40/20 Distribution**: 40% Remembering/Understanding, 40% Applying (2-step vignettes), 20% Analyzing (differential comparisons).

## 🚫 STRICT EXCLUSION RULES (CRITICAL):
- Absolutely NEVER generate cards for course mechanics, syllabus rules, homework logistics, exam dates, or textbook chapter timelines.
- Discard all conversational tangents, professor jokes, rhetorical introductions, and classroom management chatter from transcripts.
- NO binary (Yes/No) questions, NO unranked lists ("List the 5..."), NO spoiler prompts.

ALL COMBINED SOURCE MATERIALS:
<source_material>
${sourcesText}
</source_material>

## RESPONSE FORMAT

Return valid JSON with this exact structure:
{
  "flashcards": [
    {
      "front": "Atomic prompt or cloze deletion with domain context tag (e.g. '[Cardiology: Anatomy] Which valve...')",
      "back": "Concise, definitive answer (<15 words, speakable in a single breath)",
      "concept": "Major overarching theme (Group cards under 3-5 themes across the entire deck)",
      "card_type": "Basic_QA | Two_Step_Vignette | Differential | Cloze",
      "conceptual_lens": "Attributes | Differences | Parts_Wholes | Causes_Effects | Implications",
      "bloom_level": "Remembering | Understanding | Applying | Analyzing",
      "pedagogical_rationale": "One-line justification synthesizing insights across sources",
      "concrete_example": "A concrete real-world scenario or analogy illustrating this concept",
      "common_mistake": "A frequent student misconception or trap to avoid",
      "mnemonic": "An intuitive memory hook, acronym, or vivid mental visual",
      "checkpoints": ["Key idea 1 student must recall", "Key idea 2 student must recall"]
    }
  ],
  "active_recall": [
    {
      "question": "Deep conceptual inquiry starting with Why/How/Explain the mechanism of... or 2-step scenario analysis",
      "model_answer": "Complete, structured explanation with key conceptual checkpoints for mastery",
      "concept": "Major overarching theme (Must match one of the 3-5 themes across the deck)",
      "card_type": "Two_Step_Vignette | Differential",
      "conceptual_lens": "Causes_Effects | Differences | Implications",
      "bloom_level": "Understanding | Applying | Analyzing",
      "pedagogical_rationale": "Synthesis rationale",
      "concrete_example": "A real-world application or case study",
      "common_mistake": "A common reasoning flaw or incorrect assumption",
      "mnemonic": "Optional memory aid or mental framework",
      "checkpoints": ["Key conceptual criterion 1", "Key conceptual criterion 2"]
    }
  ]
}

## GENERATION CEILINGS & PEDAGOGICAL TARGETS
- Generate approximately ${targetFlashcards} flashcards (calibrated to the pedagogical sweet spot of 12-16 items).
- Generate approximately ${targetActiveRecall} active recall questions (calibrated to 3-5 high-impact questions).
- Cover every essential concept triangulated across the sources without padding or trivial cards.

## FORMATTING RULES
1. Wrap all mathematical equations, formulas, variables, and scientific expressions in standard LaTeX delimiters ($...$ for inline or $$...$$ for block math).
2. Strict Grounding: Strictly ground all items in the provided <source_material>. No external fabrications.${dedupSection}

Return ONLY valid JSON. No markdown fences. No preamble.`
}

/**
 * Build a prompt that formats math equations and formulas into LaTeX delimiters.
 */
export function buildFormatMathEquationsPrompt(text: string): string {
  return `You are an expert mathematical and scientific typesetter and flashcard formatter.
Your task is to take the provided text and convert any raw mathematical equations, formulas, variables, exponents, fractions, chemical formulas, or scientific expressions into properly formatted LaTeX.

Guidelines:
1. Wrap inline math expressions in single dollar signs, like $x^3$, $a^2 + b^2 = c^2$, $\\frac{a}{b}$, or $E = mc^2$.
2. Wrap standalone or multi-line equations in double dollar signs ($$ ... $$) if appropriate.
3. Keep non-mathematical text, punctuation, card structure, and separators (such as '...', ';', tabs, commas, newlines) EXACTLY intact.
4. If text already has valid LaTeX delimiters ($ or $$), preserve it properly.
5. Fix raw expressions such as "x^3" -> "$x^3$", "sqrt(x)" -> "$\\sqrt{x}$", "x_1" -> "$x_1$", "1/2" -> "$\\frac{1}{2}$", "H2O" or "H_2O" -> "$\\text{H}_2\\text{O}$".
6. Return ONLY the final formatted text. Do NOT wrap your entire response in markdown code fences (\`\`\`). Do NOT include conversational commentary or explanations.

TEXT TO FORMAT:
${text}`
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENHANCED RESPONSE PARSERS
// ═══════════════════════════════════════════════════════════════════════════════

const VALID_CONCEPTUAL_LENSES = ['Attributes', 'Differences', 'Parts_Wholes', 'Causes_Effects', 'Implications'] as const
const VALID_BLOOM_LEVELS = ['Remembering', 'Understanding', 'Applying', 'Analyzing'] as const
const VALID_CARD_TYPOLOGIES = ['Basic_QA', 'Two_Step_Vignette', 'Differential', 'Image_Occlusion', 'Cloze'] as const

function parseConceptualLens(val: unknown): ConceptualLens | undefined {
  if (typeof val === 'string' && VALID_CONCEPTUAL_LENSES.includes(val as ConceptualLens)) {
    return val as ConceptualLens
  }
  return undefined
}

function parseBloomLevel(val: unknown): BloomLevel | undefined {
  if (typeof val === 'string' && VALID_BLOOM_LEVELS.includes(val as BloomLevel)) {
    return val as BloomLevel
  }
  return undefined
}

function parseCardTypology(val: unknown): CardTypology | undefined {
  if (typeof val === 'string' && VALID_CARD_TYPOLOGIES.includes(val as CardTypology)) {
    return val as CardTypology
  }
  return undefined
}

/**
 * Parse the card generation response (basic format)
 */
export function parseCardGenerationResponse(responseText: string): GeneratedCards {
  const cleaned = cleanMarkdownFences(responseText)

  let parsed: any
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    parsed = JSON.parse(repairJSONString(cleaned))
  }

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }
  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  // Validate flashcard structure
  const flashcards = parsed.flashcards.map((fc: { front?: string; back?: string }) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return { front: cleanCardBrackets(fc.front), back: cleanCardBrackets(fc.back) }
  })

  // Validate active recall structure
  const active_recall = parsed.active_recall.map((ar: { question?: string; model_answer?: string }) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return { question: cleanCardBrackets(ar.question), model_answer: cleanCardBrackets(ar.model_answer) }
  })

  return { flashcards, active_recall }
}

/**
 * Parse the evaluation response
 */
export function parseEvaluationResponse(responseText: string): EvaluationResult {
  const cleaned = cleanMarkdownFences(responseText)

  let parsed: any
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    parsed = JSON.parse(repairJSONString(cleaned))
  }

  if (typeof parsed.correct !== 'boolean') {
    throw new Error('Invalid evaluation response: missing correct field')
  }
  if (typeof parsed.score !== 'number') {
    throw new Error('Invalid evaluation response: missing score field')
  }
  if (typeof parsed.feedback !== 'string') {
    throw new Error('Invalid evaluation response: missing feedback field')
  }

  let matched_concepts: string[] | undefined
  let missing_concepts: string[] | undefined

  if (Array.isArray(parsed.key_points_analyzed)) {
    matched_concepts = parsed.key_points_analyzed
      .filter((k: any) => k && (k.status === 'recalled' || k.status === 'partially_recalled'))
      .map((k: any) => (typeof k.point === 'string' ? k.point : String(k?.point || k)))
    missing_concepts = parsed.key_points_analyzed
      .filter((k: any) => k && k.status === 'missed')
      .map((k: any) => (typeof k.point === 'string' ? k.point : String(k?.point || k)))
  } else {
    if (Array.isArray(parsed.matched_concepts)) {
      matched_concepts = parsed.matched_concepts.filter((c: unknown) => typeof c === 'string')
    }
    if (Array.isArray(parsed.missing_concepts)) {
      missing_concepts = parsed.missing_concepts.filter((c: unknown) => typeof c === 'string')
    }
  }

  return {
    correct: parsed.correct,
    score: parsed.score,
    feedback: parsed.feedback,
    matched_concepts,
    missing_concepts
  }
}

/**
 * Parse the auto-card generation response (extended format with subtypes, Bloom level, conceptual lens, etc.)
 */
export function parseAutoCardResponse(responseText: string): AutoGeneratedCards {
  const cleaned = cleanMarkdownFences(responseText)

  let parsed: any
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    parsed = JSON.parse(repairJSONString(cleaned))
  }

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }
  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  const validSubtypes = ['definition', 'mechanism', 'application', 'discrimination'] as const
  type CardSubtype = typeof validSubtypes[number]

  const parseSubtype = (val: unknown): CardSubtype | undefined =>
    validSubtypes.includes(val as CardSubtype) ? (val as CardSubtype) : undefined

  const flashcards = parsed.flashcards.map((fc: Record<string, unknown>) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return {
      front: cleanCardBrackets(fc.front),
      back: cleanCardBrackets(fc.back),
      concept: typeof fc.concept === 'string' ? cleanCardBrackets(fc.concept) : undefined,
      card_subtype: parseSubtype(fc.card_subtype),
      card_type: parseCardTypology(fc.card_type),
      conceptual_lens: parseConceptualLens(fc.conceptual_lens),
      bloom_level: parseBloomLevel(fc.bloom_level),
      pedagogical_rationale: typeof fc.pedagogical_rationale === 'string' ? cleanCardBrackets(fc.pedagogical_rationale) : undefined,
      source_marker: typeof fc.source_marker === 'string' ? cleanCardBrackets(fc.source_marker) : undefined,
      concrete_example: typeof fc.concrete_example === 'string' ? cleanCardBrackets(fc.concrete_example) : undefined,
      common_mistake: typeof fc.common_mistake === 'string' ? cleanCardBrackets(fc.common_mistake) : undefined,
      mnemonic: typeof fc.mnemonic === 'string' ? cleanCardBrackets(fc.mnemonic) : undefined,
      checkpoints: Array.isArray(fc.checkpoints) ? fc.checkpoints.map(String) : undefined
    } as AutoGeneratedFlashcard
  })

  const active_recall = parsed.active_recall.map((ar: Record<string, unknown>) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return {
      question: cleanCardBrackets(ar.question),
      model_answer: cleanCardBrackets(ar.model_answer),
      concept: typeof ar.concept === 'string' ? cleanCardBrackets(ar.concept) : undefined,
      card_subtype: typeof ar.card_subtype === 'string' ? ar.card_subtype : undefined,
      card_type: parseCardTypology(ar.card_type),
      conceptual_lens: parseConceptualLens(ar.conceptual_lens),
      bloom_level: parseBloomLevel(ar.bloom_level),
      pedagogical_rationale: typeof ar.pedagogical_rationale === 'string' ? cleanCardBrackets(ar.pedagogical_rationale) : undefined,
      source_marker: typeof ar.source_marker === 'string' ? cleanCardBrackets(ar.source_marker) : undefined,
      emphasis_marker_detected: typeof ar.emphasis_marker_detected === 'string' ? cleanCardBrackets(ar.emphasis_marker_detected) : undefined,
      concrete_example: typeof ar.concrete_example === 'string' ? cleanCardBrackets(ar.concrete_example) : undefined,
      common_mistake: typeof ar.common_mistake === 'string' ? cleanCardBrackets(ar.common_mistake) : undefined,
      mnemonic: typeof ar.mnemonic === 'string' ? cleanCardBrackets(ar.mnemonic) : undefined,
      checkpoints: Array.isArray(ar.checkpoints) ? ar.checkpoints.map(String) : undefined
    } as AutoGeneratedActiveRecall
  })

  return { flashcards, active_recall }
}

/**
 * Parse a flashcard-only response
 */
export function parseFlashcardResponse(responseText: string): AutoGeneratedFlashcard[] {
  const cleaned = cleanMarkdownFences(responseText)

  let parsed: any
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    parsed = JSON.parse(repairJSONString(cleaned))
  }

  if (!parsed.flashcards || !Array.isArray(parsed.flashcards)) {
    throw new Error('Invalid response: missing flashcards array')
  }

  const validSubtypes = ['definition', 'mechanism', 'application', 'discrimination'] as const
  type CardSubtype = typeof validSubtypes[number]
  const parseSubtype = (val: unknown): CardSubtype | undefined =>
    validSubtypes.includes(val as CardSubtype) ? (val as CardSubtype) : undefined

  return parsed.flashcards.map((fc: Record<string, unknown>) => {
    if (typeof fc.front !== 'string' || typeof fc.back !== 'string') {
      throw new Error('Invalid flashcard: missing front or back')
    }
    return {
      front: cleanCardBrackets(fc.front),
      back: cleanCardBrackets(fc.back),
      concept: typeof fc.concept === 'string' ? cleanCardBrackets(fc.concept) : undefined,
      card_subtype: parseSubtype(fc.card_subtype),
      card_type: parseCardTypology(fc.card_type),
      conceptual_lens: parseConceptualLens(fc.conceptual_lens),
      bloom_level: parseBloomLevel(fc.bloom_level),
      pedagogical_rationale: typeof fc.pedagogical_rationale === 'string' ? cleanCardBrackets(fc.pedagogical_rationale) : undefined,
      source_marker: typeof fc.source_marker === 'string' ? cleanCardBrackets(fc.source_marker) : undefined,
      concrete_example: typeof fc.concrete_example === 'string' ? cleanCardBrackets(fc.concrete_example) : undefined,
      common_mistake: typeof fc.common_mistake === 'string' ? cleanCardBrackets(fc.common_mistake) : undefined,
      mnemonic: typeof fc.mnemonic === 'string' ? cleanCardBrackets(fc.mnemonic) : undefined,
      checkpoints: Array.isArray(fc.checkpoints) ? fc.checkpoints.map(String) : undefined
    } as AutoGeneratedFlashcard
  })
}

/**
 * Parse an active-recall-only response
 */
export function parseActiveRecallResponse(
  responseText: string
): AutoGeneratedActiveRecall[] {
  const cleaned = cleanMarkdownFences(responseText)

  let parsed: any
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    parsed = JSON.parse(repairJSONString(cleaned))
  }

  if (!parsed.active_recall || !Array.isArray(parsed.active_recall)) {
    throw new Error('Invalid response: missing active_recall array')
  }

  return parsed.active_recall.map((ar: Record<string, unknown>) => {
    if (typeof ar.question !== 'string' || typeof ar.model_answer !== 'string') {
      throw new Error('Invalid active recall: missing question or model_answer')
    }
    return {
      question: cleanCardBrackets(ar.question),
      model_answer: cleanCardBrackets(ar.model_answer),
      concept: typeof ar.concept === 'string' ? cleanCardBrackets(ar.concept) : undefined,
      card_subtype: typeof ar.card_subtype === 'string' ? ar.card_subtype : undefined,
      card_type: parseCardTypology(ar.card_type),
      conceptual_lens: parseConceptualLens(ar.conceptual_lens),
      bloom_level: parseBloomLevel(ar.bloom_level),
      pedagogical_rationale: typeof ar.pedagogical_rationale === 'string' ? cleanCardBrackets(ar.pedagogical_rationale) : undefined,
      source_marker: typeof ar.source_marker === 'string' ? cleanCardBrackets(ar.source_marker) : undefined,
      emphasis_marker_detected: typeof ar.emphasis_marker_detected === 'string' ? cleanCardBrackets(ar.emphasis_marker_detected) : undefined,
      concrete_example: typeof ar.concrete_example === 'string' ? cleanCardBrackets(ar.concrete_example) : undefined,
      common_mistake: typeof ar.common_mistake === 'string' ? cleanCardBrackets(ar.common_mistake) : undefined,
      mnemonic: typeof ar.mnemonic === 'string' ? cleanCardBrackets(ar.mnemonic) : undefined,
      checkpoints: Array.isArray(ar.checkpoints) ? ar.checkpoints.map(String) : undefined
    } as AutoGeneratedActiveRecall
  })
}
